// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB035-Vfv1MJOkJ_Ei7ejhx1d01gOXnQjM',
    appId: '1:640307694277:web:d635fd363c530cc0e6feac',
    messagingSenderId: '640307694277',
    projectId: 'pharmaconnect-e7eff',
    authDomain: 'pharmaconnect-e7eff.firebaseapp.com',
    storageBucket: 'pharmaconnect-e7eff.firebasestorage.app',
    measurementId: 'G-H62WEWLF8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6W54oXO7TxwIn6dtqk-DBdWHMdUErqXM',
    appId: '1:640307694277:android:cea1e07118af6fe4e6feac',
    messagingSenderId: '640307694277',
    projectId: 'pharmaconnect-e7eff',
    storageBucket: 'pharmaconnect-e7eff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS3KphKzHDJv9AvOY2fzg6WUM985Hl5uY',
    appId: '1:640307694277:ios:b8b8a562bbda960be6feac',
    messagingSenderId: '640307694277',
    projectId: 'pharmaconnect-e7eff',
    storageBucket: 'pharmaconnect-e7eff.firebasestorage.app',
    iosBundleId: 'com.example.pharmaconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS3KphKzHDJv9AvOY2fzg6WUM985Hl5uY',
    appId: '1:640307694277:ios:b8b8a562bbda960be6feac',
    messagingSenderId: '640307694277',
    projectId: 'pharmaconnect-e7eff',
    storageBucket: 'pharmaconnect-e7eff.firebasestorage.app',
    iosBundleId: 'com.example.pharmaconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB035-Vfv1MJOkJ_Ei7ejhx1d01gOXnQjM',
    appId: '1:640307694277:web:f31c7f3dbdad3022e6feac',
    messagingSenderId: '640307694277',
    projectId: 'pharmaconnect-e7eff',
    authDomain: 'pharmaconnect-e7eff.firebaseapp.com',
    storageBucket: 'pharmaconnect-e7eff.firebasestorage.app',
    measurementId: 'G-537XGEHRGJ',
  );
}
